//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2048_by_Hemok98.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Добро пожаловать в 1/8; Соберите 256 в одной ячейки;
Добро пожаловать в 1/4; Соберите 512 в одной ячейки;
Вы прошли в полуфинал; Соберите 1024 в одной ячейки;
Поздравляем с выходом в финал; Соберите 2048 в одной ячейки;
Не, ну это СУПЕРФИНАЛ; Соберите 4096 в одной ячейки;
Отличное начало;Наберите 1000 очков;
Продолжай в том же духе;Наберите 5000 очков;
Неплохо играешь;Наберите 10000 очков;
Проффесионал;Наберите 50000 очков;
В глазах двоится;Используйте удвоение первый раз;
Вас  здесь не стояло;Используйте удвоение первый раз;
5 секунд не плошло;Используйте удвоение первый раз;
Предохраняться - это хорошо;Впервые сохранитесь;
Прямиком из креогенной камеры;Впервые загрузитесь;")]
        public string achivementsParse {
            get {
                return ((string)(this["achivementsParse"]));
            }
            set {
                this["achivementsParse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string achievsContainer {
            get {
                return ((string)(this["achievsContainer"]));
            }
            set {
                this["achievsContainer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string saveStr1 {
            get {
                return ((string)(this["saveStr1"]));
            }
            set {
                this["saveStr1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string saveStr2 {
            get {
                return ((string)(this["saveStr2"]));
            }
            set {
                this["saveStr2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string saveStr3 {
            get {
                return ((string)(this["saveStr3"]));
            }
            set {
                this["saveStr3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string saveStr4 {
            get {
                return ((string)(this["saveStr4"]));
            }
            set {
                this["saveStr4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string saveStr5 {
            get {
                return ((string)(this["saveStr5"]));
            }
            set {
                this["saveStr5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string saveStr6 {
            get {
                return ((string)(this["saveStr6"]));
            }
            set {
                this["saveStr6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string saveStr7 {
            get {
                return ((string)(this["saveStr7"]));
            }
            set {
                this["saveStr7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string saveStr8 {
            get {
                return ((string)(this["saveStr8"]));
            }
            set {
                this["saveStr8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string saveStr9 {
            get {
                return ((string)(this["saveStr9"]));
            }
            set {
                this["saveStr9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int saveRecord {
            get {
                return ((int)(this["saveRecord"]));
            }
            set {
                this["saveRecord"] = value;
            }
        }
    }
}
