//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2048_by_Hemok98.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int saveRecord {
            get {
                return ((int)(this["saveRecord"]));
            }
            set {
                this["saveRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object saveCont1 {
            get {
                return ((object)(this["saveCont1"]));
            }
            set {
                this["saveCont1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object saveCont2 {
            get {
                return ((object)(this["saveCont2"]));
            }
            set {
                this["saveCont2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object saveCont3 {
            get {
                return ((object)(this["saveCont3"]));
            }
            set {
                this["saveCont3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object saveCont4 {
            get {
                return ((object)(this["saveCont4"]));
            }
            set {
                this["saveCont4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object saveCont5 {
            get {
                return ((object)(this["saveCont5"]));
            }
            set {
                this["saveCont5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object saveCont6 {
            get {
                return ((object)(this["saveCont6"]));
            }
            set {
                this["saveCont6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object saveCont7 {
            get {
                return ((object)(this["saveCont7"]));
            }
            set {
                this["saveCont7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object saveCont8 {
            get {
                return ((object)(this["saveCont8"]));
            }
            set {
                this["saveCont8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object saveCont9 {
            get {
                return ((object)(this["saveCont9"]));
            }
            set {
                this["saveCont9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object saveAchivements {
            get {
                return ((object)(this["saveAchivements"]));
            }
            set {
                this["saveAchivements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Добро пожаловать в 1/8; Соберите 256 в одной ячейки;
Добро пожаловать в 1/4; Соберите 512 в одной ячейки;
Вы прошли в полуфинал; Соберите 1024 в одной ячейки;
Поздравляем с выходом в финал; Соберите 2048 в одной ячейки;
Не, ну это СУПЕРФИНАЛ; Соберите 4096 в одной ячейки;
Отличное начало;Наберите 1000 очков;
Продолжай в том же духе;Наберите 5000 очков;
Неплохо играешь;Наберите 10000 очков;
Проффесионал;Наберите 50000 очков;
В глазах двоится;Используйте удвоение первый раз;
Вас  здесь не стояло;Используйте удвоение первый раз;
5 секунд не плошло;Используйте удвоение первый раз;
Предохраняться - это хорошо;Впервые сохранитесь;
Прямиком из креогенной камеры;Впервые загрузитесь;")]
        public string achivementsParse {
            get {
                return ((string)(this["achivementsParse"]));
            }
            set {
                this["achivementsParse"] = value;
            }
        }
    }
}
